In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


<img src="qteleport.svg">

In [2]:
Zero = np.array([[1],
                 [0]])
One  = np.array([[0],
                 [1]])

M0   = np.array([[1,0],
                 [0,0]])
M1   = np.array([[0,0],
                 [0,1]])
H    = np.array([[1,1],
                 [1,-1]])/np.sqrt(2)
CNOT = np.array([[1,0,0,0],
                 [0,1,0,0],
                 [0,0,0,1],
                 [0,0,1,0]])
CNOT2 = np.array([[1,0,0,0],
                  [0,0,0,1],
                  [0,0,1,0],
                  [0,1,0,0]])
X = np.array([[0,1],
              [1,0]])
Z = np.array([[1,0],
              [0,-1]])
I = np.eye(2)

In [3]:
def tp(*args):
    res = np.array([[1.]])
    for a in args:
        res = np.kron(res,a)
    return res

In [4]:
def n(s):
    return s/np.linalg.norm(s)

In [5]:
def meres(st,i):
    mmt0 = [[1.]]
    mmt1 = [[1.]]
    for x in range(np.int(np.log2(len(st)))):
        Op0 = I if x!=i else M0
        Op1 = I if x!=i else M1
        mmt0 = np.kron(mmt0,Op0)
        mmt1 = np.kron(mmt1,Op1)
        
    if np.random.ranf() <= np.sum(mmt0 * np.dot(st,st.T)):
        return 0,n(np.dot(mmt0,st))
    else:
        return 1,n(np.dot(mmt1,st))

In [6]:
naiv = [0,0]
for i in range(1000):
    st = tp(Zero,Zero)
    st = np.dot(tp(H,I),st)
    st = np.dot(CNOT,st)
    
    res1,st = meres(st,0)
    res2,st = meres(st,1)
    
    naiv[res2] += 1

# Nincs fénynél gyorsabb kommunikáció!
print(naiv)

[493, 507]


In [7]:
teleport = [0,0]
for i in range(1000):
    st = tp(Zero,Zero,Zero)
    st = tp(I,H,I)@st
    st = np.dot(tp(I,CNOT),st)
    st = np.dot(tp(CNOT,I),st)
    st = np.dot(tp(H,I,I),st)
    res1, st = meres(st,0)
    res2, st = meres(st,1)
    
    if res2==1:
        st = np.dot(tp(I,I,X),st)
    if res1==1:
        st = np.dot(tp(I,I,Z),st)
        
    res3, st = meres(st,2)
    teleport[res3]+=1
    
# Átvittük a bitet:
print(teleport)

[1000, 0]


## Egyéb játékok

In [8]:
α = 1/np.sqrt(5)
β = 2/np.sqrt(5)
ψ = α*Zero + β*One

In [9]:
np.kron(ψ,Zero)

array([[0.4472136 ],
       [0.        ],
       [0.89442719],
       [0.        ]])

In [10]:
np.kron(Zero,ψ)

array([[0.4472136 ],
       [0.89442719],
       [0.        ],
       [0.        ]])

In [11]:
# Kvantum swap
CNOT@CNOT2@CNOT@np.kron(ψ,Zero)

array([[0.4472136 ],
       [0.89442719],
       [0.        ],
       [0.        ]])